### ISSUE TITLE
NFS Not Working

### ISSUE THREAD

**Issue by philipithomas** [TryGhost/Ghost-Vagrant#56] opened 2014-12-30 06:59 UTC
I'm having issues with Vagrant hanging on nfs mount. I'm on a mac with Yosemite running latest Vagrant and Yosemite. 

I found some threads for other projects that encountered similar issues. Do you know of any issues with this setup or base OS?

**Comment by letsjustfixit** [comment] 2015-02-27 19:18
Well I tried using it with debian jessie (8) but didnt work either. now moving on to windows 8.1.. :)

**Comment by jaswilli** [comment] 2015-04-07 17:39
I've been unable to reproduce this issue.  Closing for now but details are welcome if anyone is able to provide steps to reproduce.

**Closed by jaswilli** 2015-04-07 17:39 UTC

**Comment by letsjustfixit** [comment] 2015-04-07 20:02
well it was fairly easy to reproduce: 
-install debian jessie 
-clone repository
-install required nfs packages stated in README
-vagrant up
there you have it :)

**Comment by SteveWooding** [comment] 2016-07-28 11:38
I had this issue, but found it was the system firewall was the cause.

Either turn your firewall off (a slight risk) or let traffic in on the port that Vagrant is requesting (it was 41159 for me, but check your firewall logs to confirm).

Hopefully this helps others that come across this issue.
